# gatus module — Deploy the Gatus health monitoring VM on the prod VLAN.
#
# Single instance, prod-only. Category 1 (no precious state, fully rebuildable).
# Config delivered via write_files — generated by generate-gatus-config.sh.

terraform {
  required_providers {
    proxmox = {
      source = "bpg/proxmox"
    }
  }
}

module "gatus" {
  source = "../proxmox-vm"

  vm_id         = var.vm_id
  vm_name       = "gatus"
  hostname      = "gatus"
  instance_id   = "gatus-prod"
  target_node    = var.target_node
  all_node_names = var.all_node_names
  image_file_id = var.image
  vlan_id       = var.vlan_id
  mac_address   = var.mac_address
  ssh_pubkey    = var.ssh_pubkey
  operator_ssh_pubkey = var.operator_ssh_pubkey
  storage_pool  = var.storage_pool
  domain        = var.domain

  ip_address    = var.ip_address
  gateway       = var.gateway
  dns_servers   = var.dns_servers
  search_domain = var.search_domain

  # Gatus: 256MB RAM, 4GB OS disk, no data disk, HA enabled
  ram_mb      = 256
  cores       = 1
  vdb_size_gb = 0
  ha_enabled  = true

  write_files = [
    {
      path        = "/run/secrets/gatus/config.yaml"
      content     = var.gatus_config
      permissions = "0444"
    },
    {
      path        = "/run/secrets/gatus/config-hash"
      content     = sha256(var.gatus_config)
      permissions = "0444"
    },
    {
      path        = "/run/secrets/certbot/pdns-api-key"
      content     = var.pdns_api_key
      permissions = "0400"
    },
    {
      path        = "/run/secrets/certbot/acme-server-url"
      content     = var.acme_server_url
      permissions = "0400"
    },
    {
      path        = "/run/secrets/certbot/pdns-api-servers"
      content     = var.pdns_api_servers
      permissions = "0400"
    }
  ]
}
