# gatus module — Deploy the Gatus health monitoring VM on the prod VLAN.
#
# Single instance, prod-only. Category 1 (no precious state, fully rebuildable).
# Config delivered via write_files — generated by generate-gatus-config.sh.

terraform {
  required_providers {
    proxmox = {
      source = "bpg/proxmox"
    }
  }
}

module "gatus" {
  source = "../proxmox-vm"

  # #690: tie the gatus VM to the fail-closed config guard so the precondition
  # is evaluated on ANY plan/apply that includes the VM — including a targeted
  # `-target=module.gatus.module.gatus...` of the inner consumer, which would
  # otherwise skip the sibling terraform_data.config_guard and let an empty
  # config reach write_files. depends_on only orders (no extra replacement).
  depends_on = [terraform_data.config_guard]

  vm_id               = var.vm_id
  vm_name             = "gatus"
  hostname            = "gatus"
  instance_id         = "gatus-prod"
  target_node         = var.target_node
  all_node_names      = var.all_node_names
  image_file_id       = var.image
  vlan_id             = var.vlan_id
  mac_address         = var.mac_address
  ssh_pubkey          = var.ssh_pubkey
  operator_ssh_pubkey = var.operator_ssh_pubkey
  storage_pool        = var.storage_pool
  tags                = var.tags
  domain              = var.domain
  start_vms             = var.start_vms
  register_ha           = var.register_ha
  replication_policy_on = var.replication_policy_on

  ssh_host_key_private = var.ssh_host_key_private
  ssh_host_key_public  = var.ssh_host_key_public
  extra_ca_cert        = var.extra_ca_cert

  ip_address    = var.ip_address
  gateway       = var.gateway
  dns_servers   = var.dns_servers
  search_domain = var.search_domain

  # Gatus: 512MB RAM, 4GB OS disk, no data disk, HA enabled.
  # 512 (not 256) to give certbot-renew its Python interpreter peak (~50 MiB
  # virt, ~25 MiB rss) headroom alongside gatus.service. With 256 MB the
  # certbot timer reliably OOM-kills, accumulates kernel_oom_total, and trips
  # validate.sh's check-service-restart-loop threshold (>=3). Matches vault's
  # ram_mb — next sibling above the 256-MB baseline. See #420.
  # The floor is also asserted by tests/test_gatus_ram_floor.sh.
  ram_mb      = 512
  cores       = 1
  vdb_size_gb = 0
  ha_enabled  = true

  vault_approle_role_id   = var.vault_approle_role_id
  vault_approle_secret_id = var.vault_approle_secret_id

  write_files = [
    {
      path        = "/run/secrets/gatus/config.yaml"
      content     = var.gatus_config
      permissions = "0444"
    },
    {
      path        = "/run/secrets/gatus/config-hash"
      content     = sha256(var.gatus_config)
      permissions = "0444"
    },
    {
      path        = "/run/secrets/certbot/pdns-api-key"
      content     = var.pdns_api_key
      permissions = "0400"
    },
    {
      path        = "/run/secrets/certbot/acme-server-url"
      content     = var.acme_server_url
      permissions = "0400"
    },
    {
      path        = "/run/secrets/certbot/pdns-api-servers"
      content     = var.pdns_api_servers
      permissions = "0400"
    }
  ]
}

# Fail-closed guard on the generated monitoring config (#690).
#
# site/gatus/config.yaml is a generated build artifact (generate-gatus-config.sh),
# not tracked in git. When it is absent the root module passes gatus_config="" (the
# fileexists() ternary keeps `tofu validate` green in the pre-build validate stage);
# an empty / zero-endpoint config makes gatus crash-loop ("configuration should
# contain at least 1 endpoint") and takes prod monitoring down. The precondition
# below evaluates at PLAN/apply time only (not at validate), so it fails a real
# deploy loudly while leaving the artifact-absent validate stage passing. This is
# the second, defence-in-depth guard behind each deploy authority generating the
# config in-path (CI build:merge, rebuild-cluster.sh, safe-apply.sh).
#
# terraform_data is a built-in resource (no provider), so the guard adds no
# dependency. The condition requires the FIRST endpoint to carry a non-empty,
# non-placeholder `url` string — every endpoint generate-gatus-config.sh emits
# has a real url.
#
# #704: the original guard, can(yamldecode(...).endpoints[0]), was fail-OPEN for
# malformed-but-non-empty lists — endpoints:[null], endpoints:[x] (scalar), and
# endpoints:[{}] all made endpoints[0] indexable and passed. This guard closes
# that hole and goes one step further than a bare can(...endpoints[0].url):
#   - length(...url) errors (→ try false) on [null], [x], [{}] (no .url attr) and
#     on url:null (length(null) errors), and is 0 on url:"";
#   - the != "null" clause rejects the literal placeholder url:"null" that a
#     mikefarah `yq -r` on a missing key would have produced pre-#704.
# It stays a strict superset of the old guard for the empty cases — empty string,
# missing key, empty list [], and scalar `endpoints:` all error on the
# index/attribute access and fail closed via try(...). The generator's own #704
# null-guards are the PRIMARY fix (they refuse to emit "prod.null"/url:"null"
# endpoints at all); this is the second, defence-in-depth guard at plan time.
resource "terraform_data" "config_guard" {
  input = sha256(var.gatus_config)

  lifecycle {
    precondition {
      condition     = try(length(yamldecode(var.gatus_config).endpoints[0].url) > 0 && yamldecode(var.gatus_config).endpoints[0].url != "null", false)
      error_message = "gatus_config has no usable endpoints — refusing to deploy an empty or malformed prod monitoring config (#690/#704). site/gatus/config.yaml is a generated artifact; run framework/scripts/generate-gatus-config.sh > site/gatus/config.yaml (CI build:merge, rebuild-cluster.sh, and safe-apply.sh do this in-path automatically)."
    }
  }
}
