#!/usr/bin/env bash
# build-all-images.sh — Build every role from image manifests.
#
# Reads roles from framework/images.yaml (infrastructure) and site/images.yaml
# (site-specific applications), merges them (erroring on duplicates), and builds
# each role via build-image.sh.
#
# Sequential builds share the nix store dependency tree: the first role builds
# the shared closure (base.nix, nixpkgs), subsequent roles find those derivations
# cached and only build role-specific packages.
#
# Usage:
#   framework/scripts/build-all-images.sh [--dev]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
VM_SCOPE_SCRIPT="${SCRIPT_DIR}/vm-scope.sh"

# Validate config consistency before building
VALIDATE_SCRIPT="${SCRIPT_DIR}/validate-site-config.sh"
if [[ -x "$VALIDATE_SCRIPT" ]]; then
  "$VALIDATE_SCRIPT" || exit 1
fi

if [[ ! -x "$VM_SCOPE_SCRIPT" ]]; then
  echo "ERROR: vm-scope.sh not found or not executable: ${VM_SCOPE_SCRIPT}" >&2
  exit 1
fi
"$VM_SCOPE_SCRIPT" validate || exit 1

FRAMEWORK_MANIFEST="${REPO_DIR}/framework/images.yaml"
SITE_MANIFEST="${REPO_DIR}/site/images.yaml"

DEV_FLAG=""
for arg in "$@"; do
  case "$arg" in
    --dev) DEV_FLAG="--dev" ;;
    *)
      echo "ERROR: Unknown argument: $arg" >&2
      echo "Usage: $(basename "$0") [--dev]" >&2
      exit 2
      ;;
  esac
done

# --- Read roles from both manifests ---
FRAMEWORK_ROLES=""
if [[ -f "$FRAMEWORK_MANIFEST" ]]; then
  FRAMEWORK_ROLES=$(yq -r '.roles | keys | .[]' "$FRAMEWORK_MANIFEST" 2>/dev/null || true)
fi

SITE_ROLES=""
if [[ -f "$SITE_MANIFEST" ]]; then
  SITE_ROLES=$(yq -r '.roles | keys | .[]' "$SITE_MANIFEST" 2>/dev/null || true)
fi

# --- Check for duplicate role names across manifests ---
for role in $SITE_ROLES; do
  if echo "$FRAMEWORK_ROLES" | grep -qx "$role"; then
    echo "ERROR: role '$role' exists in both framework and site manifests" >&2
    exit 1
  fi
done

ALL_ROLES="$FRAMEWORK_ROLES $SITE_ROLES"

# --- Read catalog application roles from applications.yaml ---
APPS_CONFIG="${REPO_DIR}/site/applications.yaml"
APP_ROLES=""
if [[ -f "$APPS_CONFIG" ]]; then
  APP_ROLES=$(yq -r '.applications // {} | to_entries[] | select(.value.enabled == true) | .key' "$APPS_CONFIG" 2>/dev/null || true)
fi

# Check for duplicate role names (catalog apps vs manifests)
for role in $APP_ROLES; do
  if echo "$FRAMEWORK_ROLES $SITE_ROLES" | tr ' ' '\n' | grep -qx "$role"; then
    echo "ERROR: catalog application '$role' conflicts with a role in image manifests" >&2
    exit 1
  fi
done

ALL_ROLES="$ALL_ROLES $APP_ROLES"

# --- Verify host configs exist for enabled catalog apps ---
# Host .nix files are generated by enable-app.sh, not here.
# If missing, the operator needs to run enable-app.sh first.
for role in $APP_ROLES; do
  host_file="${REPO_DIR}/site/nix/hosts/${role}.nix"
  if [[ ! -f "$host_file" ]]; then
    echo "ERROR: Host config not found for catalog app '${role}': site/nix/hosts/${role}.nix" >&2
    echo "Run 'framework/scripts/enable-app.sh ${role}' to generate it." >&2
    exit 1
  fi
done

if [[ -z "${ALL_ROLES// /}" ]]; then
  echo "ERROR: No roles found in manifests or config.yaml applications" >&2
  exit 1
fi

# --- Pre-build nix store space check ---
# When base.nix changes, every image gets a new hash. The host store
# accumulates both old and new closures. Check free space and GC if needed.
#
# Two independent triggers force host-side nix-collect-garbage:
#   1. Low free space   — host store free < NIX_MIN_FREE_GB (default 40 GiB)
#   2. Periodic maintenance — > NIX_GC_MAX_AGE_DAYS since last host GC
#
# The 40 GiB default (#469) accounts for the full build set
# (~7 NixOS images @2-3 GiB + 6 hil-boot ISOs @~1 GiB, plus old+new
# closures when base.nix rehashes). 20 GiB was too tight in practice.
#
# The periodic trigger (#472) plugs the "host disk never gets low but
# dead paths accumulate for weeks" hole that only shows up as
# unrelated qemu segfaults months later.

GC_ROOT_DIR="${REPO_DIR}/build/.gc-roots"
GC_TIMESTAMP_FILE="${GC_ROOT_DIR}/.last-host-gc"
NIX_GC_MAX_AGE_DAYS="${NIX_GC_MAX_AGE_DAYS:-14}"

# Validate env-var thresholds — set -u would otherwise turn a non-integer
# into an obscure "unbound variable" error deep inside an arithmetic
# comparison (codex P2). NIX_MIN_FREE_GB is validated later at first use
# because check_store_space accepts a per-call override.
if ! [[ "$NIX_GC_MAX_AGE_DAYS" =~ ^[1-9][0-9]*$ ]]; then
  echo "ERROR: NIX_GC_MAX_AGE_DAYS must be a positive integer (got: '$NIX_GC_MAX_AGE_DAYS')" >&2
  echo "  Set NIX_GC_MAX_AGE_DAYS to an integer >= 1 (default: 14)" >&2
  exit 2
fi

# Echo free GiB on the /nix/store filesystem. Echoes 0 if df fails or
# returns something we can't parse — callers treat 0 as "assume no space".
# -Pk forces 1024-byte blocks on BSD too (gemini P2); POSIX -P alone
# defaults to 512-byte on strict-POSIX setups.
host_store_free_gb() {
  local free_kb
  free_kb=$(df -Pk /nix/store 2>/dev/null | tail -1 | awk '{print $4}') || free_kb=""
  if [[ -z "$free_kb" ]] || ! [[ "$free_kb" =~ ^[0-9]+$ ]]; then
    echo 0
    return 0
  fi
  echo $((free_kb / 1024 / 1024))
}

# Echo days since the last host GC recorded in GC_TIMESTAMP_FILE.
# Echoes 999 when the file is missing, unparseable, or has a future
# timestamp (bad clock/manual edit) — caller treats "never GC'd" or
# "clock-skewed" as "must GC now" (codex P2).
gc_age_days() {
  if [[ ! -f "$GC_TIMESTAMP_FILE" ]]; then
    echo 999
    return 0
  fi
  local ts_epoch now_epoch
  ts_epoch=$(cat "$GC_TIMESTAMP_FILE" 2>/dev/null) || ts_epoch=""
  if [[ -z "$ts_epoch" ]] || ! [[ "$ts_epoch" =~ ^[0-9]+$ ]]; then
    echo 999
    return 0
  fi
  now_epoch=$(date -u +%s)
  # Future timestamp — clock skew or manual edit — treat as overdue.
  if (( ts_epoch > now_epoch )); then
    echo 999
    return 0
  fi
  echo $(( (now_epoch - ts_epoch) / 86400 ))
}

# Root-aware host GC. Preserves any current image closure symlinked
# under build/.gc-roots/. Never exits the script on non-zero — logs a
# warning and continues so a benign GC hiccup does not block the build.
# Records the timestamp ONLY on success so a persistently broken GC
# retriggers on every invocation (all three reviewers flagged the
# original "record on failure" as hiding a broken GC for 14 days).
run_host_gc() {
  local reason="${1:-unspecified}"
  echo "  Running host nix-collect-garbage (${reason})..."
  mkdir -p "$GC_ROOT_DIR" 2>/dev/null || true

  # Explicit rc capture: set -euo pipefail is on, but a benign GC error
  # (path already gone, transient store lock contention) must not kill
  # the build. Capture, log, continue.
  local gc_rc=0
  set +e
  nix-collect-garbage 2>&1 | tail -5
  gc_rc=${PIPESTATUS[0]}
  set -e

  if [[ $gc_rc -eq 0 ]]; then
    # Record success only. On failure, next invocation retries.
    # `date > file` can theoretically fail if the disk is now genuinely
    # full or GC_ROOT_DIR is unwritable — wrap it so the caller does
    # not abort under set -e (codex P2). Failure to record only means
    # the next run also GCs; not a build-blocking condition.
    if date -u +%s > "$GC_TIMESTAMP_FILE" 2>/dev/null; then
      echo "  ✓ host GC complete; timestamp recorded"
    else
      echo "  ✓ host GC complete; WARNING: failed to record timestamp at ${GC_TIMESTAMP_FILE}" >&2
    fi
  else
    echo "  WARNING: nix-collect-garbage exited ${gc_rc}; NOT recording timestamp — next invocation will retry" >&2
  fi
}

check_store_space() {
  local label="${1:-Pre-build}"
  local min_free_gb="${2:-${NIX_MIN_FREE_GB:-40}}"

  local free_gb age_days trigger=""
  free_gb=$(host_store_free_gb)
  age_days=$(gc_age_days)

  # Order matters: low space wins over periodic. Low-space also gates
  # the Darwin builder-overlay reset below; periodic-GC alone does not
  # thrash a running builder VM.
  if [[ "$free_gb" -lt "$min_free_gb" ]]; then
    trigger="low-space"
    echo ""
    echo "=== ${label}: host nix store low on space (${free_gb}GB free, need ${min_free_gb}GB) ==="
    echo "Running garbage collection and resetting builder..."
  elif [[ "$age_days" -ge "$NIX_GC_MAX_AGE_DAYS" ]]; then
    trigger="periodic-gc"
    echo ""
    echo "=== ${label}: host GC overdue (${age_days} days since last, threshold ${NIX_GC_MAX_AGE_DAYS}d) ==="
  else
    echo "${label}: ${free_gb}GB free (threshold: ${min_free_gb}GB), GC age ${age_days}d — OK"
    return 0
  fi

  # Root-aware GC: removes paths not reachable from any GC root.
  # Current images (via build/.gc-roots/ symlinks from --out-link)
  # and their shared closures are preserved.
  run_host_gc "$trigger"

  # macOS overlay reset only for actual low-space. On periodic GC alone,
  # do not disturb a running builder — its overlay is not the pressure.
  if [[ "$trigger" == "low-space" ]] && [[ "$(uname)" == "Darwin" ]]; then
    echo "  Restarting builder with fresh overlay..."
    pkill -f "qemu.*nixos.qcow2" 2>/dev/null || true
    for i in $(seq 1 15); do
      pgrep -f "qemu.*nixos.qcow2" >/dev/null 2>&1 || break
      sleep 1
    done
    rm -f "${HOME}/.nix-builder/store.img" 2>/dev/null || true
    BUILDER_START="${HOME}/.nix-builder/start-builder.sh"
    if [[ -x "$BUILDER_START" ]]; then
      bash "$BUILDER_START"
      for i in $(seq 1 24); do
        nc -z localhost 31022 2>/dev/null && break
        sleep 5
      done
    fi
  fi

  free_gb=$(host_store_free_gb)
  echo "  After GC: ${free_gb}GB free"

  if [[ "$trigger" == "low-space" ]] && [[ "$free_gb" -lt "$min_free_gb" ]]; then
    echo "WARNING: Still low on space after GC (${free_gb}GB)."
    echo "The host disk may be too small for the full build set."
  fi
}

# Reset the builder VM between builds on macOS. Each build accumulates
# outputs in the builder's writable disk (nixos.qcow2). Without reset,
# the disk fills after ~4 large images. Restarting the VM with a fresh
# nixos.qcow2 reclaims all space. The erofs store.img (read-only nix
# closure) is recreated automatically on each boot from the host store.
# SSH keys in ~/.nix-builder/keys/ persist across restarts.
reset_builder_overlay() {
  # #471: post-build reset was ignoring host-side pressure. Run a
  # light-threshold host check first so that if the host store is low
  # (or GC is overdue), we trigger host GC (and, if low-space and
  # Darwin, an overlay purge) BEFORE deciding to only purge the
  # builder qcow2. Threshold 8 mirrors the per-image `Before ${ROLE}`
  # threshold so it only fires on real host-side pressure.
  check_store_space "Post-build" 8

  if [[ "$(uname)" != "Darwin" ]]; then
    return 0
  fi
  local qcow2="${NIX_DISK_IMAGE:-${HOME}/.nix-builder/nixos.qcow2}"
  if [[ ! -f "$qcow2" ]]; then
    return 0
  fi
  local disk_used
  disk_used=$(du -m "$qcow2" 2>/dev/null | cut -f1)
  # Only reset if disk has grown significantly (>2GB of build outputs)
  if [[ "$disk_used" -gt 2000 ]]; then
    echo "  Resetting builder (${disk_used}MB used)..."
    pkill -f "qemu.*nixos.qcow2" 2>/dev/null || true
    for i in $(seq 1 15); do
      pgrep -f "qemu.*nixos.qcow2" >/dev/null 2>&1 || break
      sleep 1
    done
    rm -f "$qcow2"
    rm -f "${HOME}/.nix-builder/store.img"
    BUILDER_START="${HOME}/.nix-builder/start-builder.sh"
    if [[ -x "$BUILDER_START" ]]; then
      bash "$BUILDER_START"
      for i in $(seq 1 36); do
        if nc -z localhost 31022 2>/dev/null; then
          break
        fi
        sleep 5
      done
      if ! nc -z localhost 31022 2>/dev/null; then
        echo "  ERROR: Builder failed to restart" >&2
        return 1
      fi
    fi
  fi
}

build_control_plane_closures() {
  local build_dir="${REPO_DIR}/build"
  local json_file="${build_dir}/closure-paths.json"
  local control_plane_hosts=()
  local control_plane_hosts_raw=""
  local host=""
  local path=""
  local first=1

  control_plane_hosts_raw="$("$VM_SCOPE_SCRIPT" control-plane-built-roles)" || {
    echo "ERROR: Failed to derive control-plane host list from vm-scope.sh" >&2
    exit 1
  }
  while IFS= read -r host; do
    [[ -n "$host" ]] && control_plane_hosts+=("$host")
  done <<< "$control_plane_hosts_raw"

  if [[ ${#control_plane_hosts[@]} -eq 0 ]]; then
    echo "ERROR: vm-scope.sh returned no control-plane hosts" >&2
    exit 1
  fi

  mkdir -p "${build_dir}"
  printf '{\n' > "${json_file}"

  for host in "${control_plane_hosts[@]}"; do
    echo ""
    echo "=========================================="
    echo "Building closure: ${host}"
    echo "=========================================="

    # Keep an out-link in build/ so the closure remains GC-rooted between CI jobs.
    path="$(
      nix build \
        --print-out-paths \
        --out-link "${build_dir}/closure-${host}" \
        ".#nixosConfigurations.${host}.config.system.build.toplevel"
    )"

    if [[ -z "${path}" ]]; then
      echo "ERROR: nix build did not return a closure path for ${host}" >&2
      exit 1
    fi

    if [[ "${first}" -eq 0 ]]; then
      printf ',\n' >> "${json_file}"
    fi
    printf '  "%s": "%s"' "${host}" "${path}" >> "${json_file}"
    first=0
  done

  printf '\n}\n' >> "${json_file}"

  echo ""
  echo "Control-plane closure artifact:"
  cat "${json_file}"
}

check_store_space "Pre-build"

# --- Build each role ---
for ROLE in $ALL_ROLES; do
  # Per-image space check (lower threshold — only triggers if space
  # got tight during the build cycle from intermediate products)
  check_store_space "Before ${ROLE}" 8

  # Check if this is a catalog application (from config.yaml)
  if echo "$APP_ROLES" | tr ' ' '\n' | grep -qx "$ROLE"; then
    # Catalog application — host config is at site/nix/hosts/<app>.nix
    HOST_CONFIG="site/nix/hosts/${ROLE}.nix"
    if [[ ! -f "${REPO_DIR}/${HOST_CONFIG}" ]]; then
      echo "ERROR: Host config not found for catalog app '${ROLE}': ${HOST_CONFIG}" >&2
      echo "This should have been auto-generated above. Check catalog module exists." >&2
      exit 1
    fi

    echo ""
    echo "=========================================="
    echo "Building: ${ROLE} (catalog application)"
    echo "=========================================="

    "${SCRIPT_DIR}/build-image.sh" $DEV_FLAG "$HOST_CONFIG" "$ROLE"
    reset_builder_overlay
    continue
  fi

  # Determine which manifest contains this role
  if yq -e ".roles.${ROLE}" "$FRAMEWORK_MANIFEST" >/dev/null 2>&1; then
    MANIFEST="$FRAMEWORK_MANIFEST"
  else
    MANIFEST="$SITE_MANIFEST"
  fi

  CATEGORY=$(yq -r ".roles.${ROLE}.category" "$MANIFEST")

  echo ""
  echo "=========================================="
  echo "Building: ${ROLE} (${CATEGORY})"
  echo "=========================================="

  case "$CATEGORY" in
    nix)
      HOST_CONFIG=$(yq -r ".roles.${ROLE}.host_config" "$MANIFEST")
      "${SCRIPT_DIR}/build-image.sh" $DEV_FLAG "$HOST_CONFIG" "$ROLE"
      ;;
    external)
      BUILD_SCRIPT=$(yq -r ".roles.${ROLE}.build_script" "$MANIFEST")
      "${SCRIPT_DIR}/build-image.sh" $DEV_FLAG --external "$BUILD_SCRIPT" "$ROLE"
      ;;
    *)
      echo "ERROR: Unknown category '$CATEGORY' for role '$ROLE'" >&2
      exit 1
      ;;
  esac
  reset_builder_overlay
done

build_control_plane_closures

echo ""
echo "All images built. image-versions.auto.tfvars:"
cat "${REPO_DIR}/site/tofu/image-versions.auto.tfvars"
