#!/usr/bin/env bash
# generate-gatus-config.sh — Generate Gatus health check configuration from config.yaml.
#
# Usage: generate-gatus-config.sh [config.yaml]
#
# Reads site/config.yaml and produces a Gatus YAML config on stdout.
# The output is consumed by OpenTofu (passed to write_files on the Gatus VM).
#
# Idempotent: running twice with the same config.yaml produces identical output.

set -euo pipefail

find_repo_root() {
  local dir
  dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  while [[ "$dir" != "/" ]]; do
    [[ -f "${dir}/flake.nix" ]] && { echo "$dir"; return 0; }
    dir="$(dirname "$dir")"
  done
  echo "ERROR: Could not find repo root" >&2
  exit 1
}

REPO_DIR="$(find_repo_root)"
CONFIG="${1:-${REPO_DIR}/site/config.yaml}"
APPS_CONFIG="${REPO_DIR}/site/applications.yaml"
source "${REPO_DIR}/framework/scripts/certbot-cluster.sh"
source "${REPO_DIR}/framework/scripts/github-publish-lib.sh"

if [[ ! -f "$CONFIG" ]]; then
  echo "ERROR: Config file not found: $CONFIG" >&2
  exit 1
fi

# --- Read values from config.yaml ---
DNS_DOMAIN="prod.$(yq -r '.domain' "$CONFIG")"
DNS1_IP=$(yq -r '.vms.dns1_prod.ip' "$CONFIG")
DNS2_IP=$(yq -r '.vms.dns2_prod.ip' "$CONFIG")
VAULT_IP=$(yq -r '.vms.vault_prod.ip' "$CONFIG")
PBS_IP=$(yq -r '.vms.pbs.ip' "$CONFIG")
GITLAB_IP=$(yq -r '.vms.gitlab.ip' "$CONFIG")
GATUS_IP=$(yq -r '.vms.gatus.ip' "$CONFIG")
TESTAPP_PROD_IP=$(yq -r '.vms.testapp_prod.ip // ""' "$CONFIG")
NAS_IP=$(yq -r '.nas.ip' "$CONFIG")
HEALTH_PORT=$(yq -r '.replication.health_port' "$CONFIG")
STORAGE_POOL=$(yq -r '.proxmox.storage_pool' "$CONFIG")
ACME_MODE=$(yq -r '.acme // "production"' "$CONFIG")
CERT_GROUP="$(certbot_cluster_gatus_cert_group)"

SMTP_HOST=$(yq -r '.email.smtp_host' "$CONFIG")
SMTP_PORT=$(yq -r '.email.smtp_port' "$CONFIG")
EMAIL_FROM="gatus@$(yq -r '.domain' "$CONFIG")"
EMAIL_TO=$(yq -r '.email.to' "$CONFIG")
GITHUB_REMOTE_URL=$(yq -r '.github.remote_url // ""' "$CONFIG")
PUBLISH_GITHUB_ENABLED=$(yq -r '.publish.github.enabled // false' "$CONFIG")
GATUS_GITHUB_EXPECTED_SOURCE_COMMIT="${GATUS_GITHUB_EXPECTED_SOURCE_COMMIT:-}"

# Read node management IPs
NODE_COUNT=$(yq -r '.nodes | length' "$CONFIG")

cat <<EOF
# Gatus configuration — generated by generate-gatus-config.sh
# Source: site/config.yaml
# Do not edit manually — regenerate from config.yaml.

alerting:
  email:
    from: "${EMAIL_FROM}"
    host: "${SMTP_HOST}"
    port: ${SMTP_PORT}
    to: "${EMAIL_TO}"
    default-alert:
      enabled: true
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 2

endpoints:
EOF

if [[ -n "${GATUS_GITHUB_EXPECTED_SOURCE_COMMIT}" && "${PUBLISH_GITHUB_ENABLED}" == "true" ]]; then
  # Issue #294: only emit the GitHub mirror endpoint when publishing is opted in.
  # Callers (build:merge in CI, rebuild-cluster.sh on the workstation) set
  # GATUS_GITHUB_EXPECTED_SOURCE_COMMIT unconditionally, so the env-var alone is
  # not sufficient to gate emission — the URL would be empty for downstream
  # adopters with publishing disabled, and github_remote_to_raw_metadata_url
  # would crash the script under set -e.
  GITHUB_METADATA_URL="$(github_remote_to_raw_metadata_url "${GITHUB_REMOTE_URL}")"
  cat <<EOF
  # --- GitHub Publish Mirror ---
  - name: github-mirror-main
    group: publishing
    url: "${GITHUB_METADATA_URL}"
    conditions:
      - "[STATUS] == 200"
      # Issue #301: Gatus 5.x condition parser keeps quotes as part of the
      # string literal, so a quoted RHS never matches the jsonpath-resolved
      # LHS (which has no surrounding quotes). Compare against the bare
      # SHA — same convention as other [BODY].field == identifier checks
      # in this file (e.g. [BODY].status == healthy).
      - "[BODY].source_commit == ${GATUS_GITHUB_EXPECTED_SOURCE_COMMIT}"
    interval: 10m
    alerts:
      - type: email
        failure-threshold: 3
        success-threshold: 2

EOF
fi

cat <<EOF
  # --- DNS Health ---
  - name: dns1-prod
    group: dns
    url: "${DNS1_IP}"
    dns:
      query-name: "vault.${DNS_DOMAIN}"
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"
    interval: 30s
    alerts:
      - type: email

  - name: dns2-prod
    group: dns
    url: "${DNS2_IP}"
    dns:
      query-name: "vault.${DNS_DOMAIN}"
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"
    interval: 30s
    alerts:
      - type: email

  # --- Vault Health ---
  - name: vault-prod
    group: secrets
    url: "https://${VAULT_IP}:8200/v1/sys/health"
    client:
      insecure: true
    conditions:
      - "[STATUS] == 200"
    interval: 30s
    alerts:
      - type: email

EOF

if [[ "${ACME_MODE}" == "production" ]]; then
  cat <<EOF
  # --- Certificate Health (production ACME only) ---
EOF
  while IFS=$'\t' read -r endpoint_name _ endpoint_ip endpoint_port _; do
    [[ -z "${endpoint_name}" ]] && continue
    cat <<EOF
  - name: ${endpoint_name}
    group: ${CERT_GROUP}
    url: "https://${endpoint_ip}:${endpoint_port}"
    client:
      insecure: true
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 14d"
    interval: 1h
    alerts:
      - type: email
        failure-threshold: 1

EOF
  done < <(certbot_cluster_gatus_cert_monitor_records "${CONFIG}" "${APPS_CONFIG}" "${REPO_DIR}")
else
  cat <<EOF
  # Certificate checks disabled (acme: ${ACME_MODE})
EOF
fi

cat <<EOF

  # --- PBS Health ---
  - name: pbs
    group: backups
    url: "https://${PBS_IP}:8007"
    client:
      insecure: true
    conditions:
      - "[STATUS] < 500"
    interval: 60s
    alerts:
      - type: email

  # --- GitLab Health ---
  - name: gitlab
    group: services
    url: "https://${GITLAB_IP}"
    client:
      insecure: true
    conditions:
      - "[STATUS] < 500"
    interval: 60s
    alerts:
      - type: email

  # --- Testapp Health ---
EOF

if [[ -n "$TESTAPP_PROD_IP" ]]; then
  cat <<EOF
  - name: testapp-prod
    group: applications
    url: "http://${TESTAPP_PROD_IP}:8080/"
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == healthy"
    interval: 60s
    alerts:
      - type: email

EOF
fi

# --- Catalog Application Health (from config.yaml applications block) ---
# Health port/path come from the catalog module's metadata.yaml, not config.yaml.
APP_NAMES=$(yq -r '.applications // {} | to_entries[] | select(.value.enabled == true and .value.monitor == true) | .key' "$APPS_CONFIG" 2>/dev/null || true)
for APP in $APP_NAMES; do
  if [[ "$APP" == "workstation" ]]; then
    continue
  fi

  APP_IP=$(yq -r ".applications.${APP}.environments.prod.ip // \"\"" "$APPS_CONFIG")
  HEALTH_FILE="${REPO_DIR}/framework/catalog/${APP}/health.yaml"
  HEALTH_PORT_APP=$(yq -r '.port // ""' "$HEALTH_FILE" 2>/dev/null)
  HEALTH_PATH_APP=$(yq -r '.path // ""' "$HEALTH_FILE" 2>/dev/null)
  if [[ -n "$APP_IP" && "$APP_IP" != "null" ]]; then
    cat <<EOF
  # --- ${APP} Health ---
  - name: ${APP}-prod
    group: applications
    url: "https://${APP_IP}:${HEALTH_PORT_APP}${HEALTH_PATH_APP}"
    client:
      insecure: true
    conditions:
      - "[STATUS] == 200"
    interval: 60s
    alerts:
      - type: email

EOF
  fi

  if [[ "$APP" == "influxdb" ]]; then
    DASHBOARD_HEALTH_FILE="${REPO_DIR}/framework/catalog/cluster-dashboard/health.yaml"
    DASHBOARD_HEALTH_PORT=$(yq -r '.port // ""' "$DASHBOARD_HEALTH_FILE" 2>/dev/null)
    DASHBOARD_HEALTH_PATH=$(yq -r '.path // ""' "$DASHBOARD_HEALTH_FILE" 2>/dev/null)
    # Trade-off: keep the app-level health check on InfluxDB's real backend
    # surface (:8086/health) and synthesize a second check for the co-hosted
    # dashboard. The nested cluster-dashboard catalog metadata is otherwise
    # invisible to the app-health inventory that Gatus consumes.
    if [[ -n "$DASHBOARD_HEALTH_PORT" && "$DASHBOARD_HEALTH_PORT" != "null" ]]; then
      cat <<EOF
  # --- ${APP} Dashboard Health ---
  - name: ${APP}-dashboard-prod
    group: applications
    url: "https://${APP_IP}:${DASHBOARD_HEALTH_PORT}${DASHBOARD_HEALTH_PATH}"
    client:
      insecure: true
    conditions:
      - "[STATUS] == 200"
    interval: 60s
    alerts:
      - type: email

EOF
    fi
  fi
done

WORKSTATION_ENABLED=$(yq -r '.applications.workstation.enabled // false' "$APPS_CONFIG" 2>/dev/null || true)
if [[ "$WORKSTATION_ENABLED" == "true" ]]; then
  WORKSTATION_HEALTH_FILE="${REPO_DIR}/framework/catalog/workstation/health.yaml"
  WORKSTATION_HEALTH_PORT=$(yq -r '.port // ""' "$WORKSTATION_HEALTH_FILE" 2>/dev/null)
  WORKSTATION_HEALTH_PATH=$(yq -r '.path // ""' "$WORKSTATION_HEALTH_FILE" 2>/dev/null)

  for WORK_ENV in prod dev; do
    if [[ "$WORK_ENV" == "dev" ]]; then
      WORK_IP=$(yq -r '.applications.workstation.environments.dev.mgmt_nic.ip // ""' "$APPS_CONFIG" 2>/dev/null || true)
    else
      WORK_IP=$(yq -r ".applications.workstation.environments.${WORK_ENV}.ip // \"\"" "$APPS_CONFIG" 2>/dev/null || true)
    fi

    [[ -z "$WORK_IP" || "$WORK_IP" == "null" ]] && continue

    cat <<EOF
  # --- Workstation ${WORK_ENV} Health ---
  - name: workstation-${WORK_ENV}
    group: workstations
    url: "https://${WORK_IP}:${WORKSTATION_HEALTH_PORT}${WORKSTATION_HEALTH_PATH}"
    client:
      insecure: true
    conditions:
      - "[STATUS] == 200"
    interval: 60s
    alerts:
      - type: email

  - name: workstation-ssh-${WORK_ENV}
    group: workstations
    url: "tcp://${WORK_IP}:22"
    conditions:
      - "[CONNECTED] == true"
    interval: 60s
    alerts:
      - type: email

EOF
  done
fi

cat <<EOF
  # --- Proxmox Cluster Health ---
EOF

for (( i=0; i<NODE_COUNT; i++ )); do
  NODE_NAME=$(yq -r ".nodes[${i}].name" "$CONFIG")
  NODE_IP=$(yq -r ".nodes[${i}].mgmt_ip" "$CONFIG")
  cat <<EOF
  - name: ${NODE_NAME}
    group: proxmox
    url: "https://${NODE_IP}:8006"
    client:
      insecure: true
    conditions:
      - "[STATUS] < 500"
    interval: 30s
    alerts:
      - type: email

EOF
done

# --- Replication Mesh Health ---
for (( i=0; i<NODE_COUNT; i++ )); do
  NODE_NAME=$(yq -r ".nodes[${i}].name" "$CONFIG")
  NODE_IP=$(yq -r ".nodes[${i}].mgmt_ip" "$CONFIG")
  cat <<EOF
  - name: repl-${NODE_NAME}
    group: replication
    url: "http://${NODE_IP}:${HEALTH_PORT}/"
    conditions:
      - "[STATUS] == 200"
      - "[BODY].replication_stale == false"
      - "[BODY].zfs_pools.${STORAGE_POOL} == healthy"
    interval: 60s
    alerts:
      - type: email

EOF
done

cat <<EOF
  # --- NAS Reachability ---
  - name: nas
    group: infrastructure
    url: "tcp://${NAS_IP}:5000"
    conditions:
      - "[CONNECTED] == true"
    interval: 60s
    alerts:
      - type: email

  # --- Placement Health (off-cluster watchdog on NAS) ---
  - name: placement-health
    group: cluster
    url: "http://${NAS_IP}:9200/"
    conditions:
      - "[STATUS] == 200"
      - "[BODY].placement_healthy == true"
    interval: 5m
    alerts:
      - type: email

  # --- Sentinel Gatus (Mutual Monitoring) ---
  - name: sentinel-gatus
    group: monitoring
    url: "http://${NAS_IP}:8080/api/v1/endpoints/statuses"
    conditions:
      - "[STATUS] == 200"
    interval: 60s
    alerts:
      - type: email
EOF
