#!/usr/bin/env bash
# generate-gatus-config.sh — Generate Gatus health check configuration from config.yaml.
#
# Usage: generate-gatus-config.sh [config.yaml]
#
# Reads site/config.yaml and produces a Gatus YAML config on stdout.
# The output is consumed by OpenTofu (passed to write_files on the Gatus VM).
#
# Idempotent: running twice with the same config.yaml produces identical output.

set -euo pipefail

find_repo_root() {
  local dir
  dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  while [[ "$dir" != "/" ]]; do
    [[ -f "${dir}/flake.nix" ]] && { echo "$dir"; return 0; }
    dir="$(dirname "$dir")"
  done
  echo "ERROR: Could not find repo root" >&2
  exit 1
}

REPO_DIR="$(find_repo_root)"
CONFIG="${1:-${REPO_DIR}/site/config.yaml}"

if [[ ! -f "$CONFIG" ]]; then
  echo "ERROR: Config file not found: $CONFIG" >&2
  exit 1
fi

# --- Read values from config.yaml ---
DNS_DOMAIN="prod.$(yq -r '.domain' "$CONFIG")"
DNS1_IP=$(yq -r '.vms.dns1_prod.ip' "$CONFIG")
DNS2_IP=$(yq -r '.vms.dns2_prod.ip' "$CONFIG")
VAULT_IP=$(yq -r '.vms.vault_prod.ip' "$CONFIG")
PBS_IP=$(yq -r '.vms.pbs.ip' "$CONFIG")
GITLAB_IP=$(yq -r '.vms.gitlab.ip' "$CONFIG")
GATUS_IP=$(yq -r '.vms.gatus.ip' "$CONFIG")
TESTAPP_PROD_IP=$(yq -r '.vms.testapp_prod.ip // ""' "$CONFIG")
NAS_IP=$(yq -r '.nas.ip' "$CONFIG")
HEALTH_PORT=$(yq -r '.replication.health_port' "$CONFIG")
STORAGE_POOL=$(yq -r '.proxmox.storage_pool' "$CONFIG")
ACME_MODE=$(yq -r '.acme // "production"' "$CONFIG")

SMTP_HOST=$(yq -r '.email.smtp_host' "$CONFIG")
SMTP_PORT=$(yq -r '.email.smtp_port' "$CONFIG")
EMAIL_FROM="gatus@$(yq -r '.domain' "$CONFIG")"
EMAIL_TO=$(yq -r '.email.to' "$CONFIG")

# Read node management IPs
NODE_COUNT=$(yq -r '.nodes | length' "$CONFIG")

cat <<EOF
# Gatus configuration — generated by generate-gatus-config.sh
# Source: site/config.yaml
# Do not edit manually — regenerate from config.yaml.

alerting:
  email:
    from: "${EMAIL_FROM}"
    host: "${SMTP_HOST}"
    port: ${SMTP_PORT}
    to: "${EMAIL_TO}"
    default-alert:
      enabled: true
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 2

endpoints:
  # --- DNS Health ---
  - name: dns1-prod
    group: dns
    url: "${DNS1_IP}"
    dns:
      query-name: "vault.${DNS_DOMAIN}"
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"
    interval: 30s
    alerts:
      - type: email

  - name: dns2-prod
    group: dns
    url: "${DNS2_IP}"
    dns:
      query-name: "vault.${DNS_DOMAIN}"
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"
    interval: 30s
    alerts:
      - type: email

  # --- Vault Health ---
  - name: vault-prod
    group: secrets
    url: "https://${VAULT_IP}:8200/v1/sys/health"
    client:
      insecure: true
    conditions:
      - "[STATUS] == 200"
    interval: 30s
    alerts:
      - type: email

$(if [[ "$ACME_MODE" == "production" ]]; then cat <<CERTS
  # --- Certificate Health (production ACME only) ---
  - name: cert-vault-prod
    group: certificates
    url: "https://${VAULT_IP}:8200"
    client:
      insecure: true
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 14d"
    interval: 1h
    alerts:
      - type: email
        failure-threshold: 1

  - name: cert-gitlab
    group: certificates
    url: "https://${GITLAB_IP}"
    client:
      insecure: true
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 14d"
    interval: 1h
    alerts:
      - type: email
        failure-threshold: 1
CERTS
else
  echo "  # Certificate checks disabled (acme: ${ACME_MODE})"
fi)

  # --- PBS Health ---
  - name: pbs
    group: backups
    url: "https://${PBS_IP}:8007"
    client:
      insecure: true
    conditions:
      - "[STATUS] < 500"
    interval: 60s
    alerts:
      - type: email

  # --- GitLab Health ---
  - name: gitlab
    group: services
    url: "https://${GITLAB_IP}"
    client:
      insecure: true
    conditions:
      - "[STATUS] < 500"
    interval: 60s
    alerts:
      - type: email

  # --- Testapp Health ---
EOF

if [[ -n "$TESTAPP_PROD_IP" ]]; then
  cat <<EOF
  - name: testapp-prod
    group: applications
    url: "http://${TESTAPP_PROD_IP}:8080/"
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == healthy"
    interval: 60s
    alerts:
      - type: email

EOF
fi

# --- Catalog Application Health (from config.yaml applications block) ---
APP_NAMES=$(yq -r '.applications // {} | to_entries[] | select(.value.enabled == true and .value.monitor == true) | .key' "$CONFIG" 2>/dev/null || true)
for APP in $APP_NAMES; do
  APP_IP=$(yq -r ".applications.${APP}.environments.prod.ip // \"\"" "$CONFIG")
  HEALTH_PORT_APP=$(yq -r ".applications.${APP}.health_port" "$CONFIG")
  HEALTH_PATH_APP=$(yq -r ".applications.${APP}.health_path" "$CONFIG")
  if [[ -n "$APP_IP" && "$APP_IP" != "null" ]]; then
    cat <<EOF
  # --- ${APP} Health ---
  - name: ${APP}-prod
    group: applications
    url: "https://${APP_IP}:${HEALTH_PORT_APP}${HEALTH_PATH_APP}"
    client:
      insecure: true
    conditions:
      - "[STATUS] == 200"
    interval: 60s
    alerts:
      - type: email

$(if [[ "$ACME_MODE" == "production" ]]; then cat <<APPCERT
  - name: cert-${APP}-prod
    group: certificates
    url: "https://${APP_IP}:${HEALTH_PORT_APP}"
    client:
      insecure: true
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 14d"
    interval: 1h
    alerts:
      - type: email
        failure-threshold: 1
APPCERT
fi)

EOF
  fi
done

cat <<EOF
  # --- Proxmox Cluster Health ---
EOF

for (( i=0; i<NODE_COUNT; i++ )); do
  NODE_NAME=$(yq -r ".nodes[${i}].name" "$CONFIG")
  NODE_IP=$(yq -r ".nodes[${i}].mgmt_ip" "$CONFIG")
  cat <<EOF
  - name: ${NODE_NAME}
    group: proxmox
    url: "https://${NODE_IP}:8006"
    client:
      insecure: true
    conditions:
      - "[STATUS] < 500"
    interval: 30s
    alerts:
      - type: email

EOF
done

# --- Replication Mesh Health ---
for (( i=0; i<NODE_COUNT; i++ )); do
  NODE_NAME=$(yq -r ".nodes[${i}].name" "$CONFIG")
  NODE_IP=$(yq -r ".nodes[${i}].mgmt_ip" "$CONFIG")
  cat <<EOF
  - name: repl-${NODE_NAME}
    group: replication
    url: "http://${NODE_IP}:${HEALTH_PORT}/"
    conditions:
      - "[STATUS] == 200"
      - "[BODY].replication_stale == false"
      - "[BODY].zfs_pools.${STORAGE_POOL} == healthy"
    interval: 60s
    alerts:
      - type: email

EOF
done

cat <<EOF
  # --- NAS Reachability ---
  - name: nas
    group: infrastructure
    url: "tcp://${NAS_IP}:5000"
    conditions:
      - "[CONNECTED] == true"
    interval: 60s
    alerts:
      - type: email

  # --- Placement Health (off-cluster watchdog on NAS) ---
  - name: placement-health
    group: cluster
    url: "http://${NAS_IP}:9200/"
    conditions:
      - "[STATUS] == 200"
      - "[BODY].placement_healthy == true"
    interval: 5m
    alerts:
      - type: email

  # --- Sentinel Gatus (Mutual Monitoring) ---
  - name: sentinel-gatus
    group: monitoring
    url: "http://${NAS_IP}:8080/api/v1/endpoints/statuses"
    conditions:
      - "[STATUS] == 200"
    interval: 60s
    alerts:
      - type: email
EOF
