#!/usr/bin/env bash
# merge-image-versions.sh — Compose image-versions.auto.tfvars from per-role fragments.
#
# Per-role build:image jobs each emit one fragment file:
#   build/image-versions/<role>.tfvars-fragment
#     containing a single line:  "<role>" = "<role>-<hash>.img"
#
# This script:
#   1. Reads the expected role list from framework/images.yaml +
#      site/images.yaml + enabled apps in site/applications.yaml
#   2. Verifies every expected role has a fragment, and no extra fragment
#      exists (drift in either direction = hard fail)
#   3. Validates each fragment matches the expected `"role" = "role-hash.img"` shape
#   4. Composes site/tofu/image-versions.auto.tfvars from the fragments in
#      sorted order (deterministic output)
#   5. For control-plane hosts (gitlab, cicd), composes build/closure-paths.json
#      from per-role build/closure-path-<host>.txt files emitted alongside
#      the image fragments

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"

FRAG_DIR="${REPO_DIR}/build/image-versions"
OUT_TFVARS="${REPO_DIR}/site/tofu/image-versions.auto.tfvars"
OUT_CLOSURES="${REPO_DIR}/build/closure-paths.json"

FRAMEWORK_MANIFEST="${REPO_DIR}/framework/images.yaml"
SITE_MANIFEST="${REPO_DIR}/site/images.yaml"
APPS_CONFIG="${REPO_DIR}/site/applications.yaml"

CONTROL_PLANE_HOSTS=(gitlab cicd)

if [[ ! -d "$FRAG_DIR" ]]; then
  echo "ERROR: Fragment directory not found: $FRAG_DIR" >&2
  echo "Per-role build jobs must run before merge." >&2
  exit 1
fi

# --- Compute expected role list ---
expected_roles=()
if [[ -f "$FRAMEWORK_MANIFEST" ]]; then
  while IFS= read -r r; do [[ -n "$r" ]] && expected_roles+=("$r"); done \
    < <(yq -r '.roles | keys | .[]' "$FRAMEWORK_MANIFEST" 2>/dev/null || true)
fi
if [[ -f "$SITE_MANIFEST" ]]; then
  while IFS= read -r r; do [[ -n "$r" ]] && expected_roles+=("$r"); done \
    < <(yq -r '.roles | keys | .[]' "$SITE_MANIFEST" 2>/dev/null || true)
fi
if [[ -f "$APPS_CONFIG" ]]; then
  while IFS= read -r r; do [[ -n "$r" ]] && expected_roles+=("$r"); done \
    < <(yq -r '.applications // {} | to_entries[] | select(.value.enabled == true) | .key' \
        "$APPS_CONFIG" 2>/dev/null || true)
fi

if [[ ${#expected_roles[@]} -eq 0 ]]; then
  echo "ERROR: No roles found in any manifest." >&2
  exit 1
fi

# Sort + dedupe for deterministic output (portable to bash 3.2).
sorted=()
while IFS= read -r r; do sorted+=("$r"); done \
  < <(printf '%s\n' "${expected_roles[@]}" | sort -u)
expected_roles=("${sorted[@]}")

# --- Verify every expected role has a fragment ---
missing=()
for role in "${expected_roles[@]}"; do
  if [[ ! -s "${FRAG_DIR}/${role}.tfvars-fragment" ]]; then
    missing+=("$role")
  fi
done
if [[ ${#missing[@]} -gt 0 ]]; then
  echo "ERROR: Missing or empty fragments for: ${missing[*]}" >&2
  echo "Each per-role build:image job must emit build/image-versions/<role>.tfvars-fragment" >&2
  exit 1
fi

# --- Verify no unexpected fragments ---
unexpected=()
for frag in "${FRAG_DIR}"/*.tfvars-fragment; do
  [[ -e "$frag" ]] || continue
  fr_role="$(basename "$frag" .tfvars-fragment)"
  found=0
  for r in "${expected_roles[@]}"; do
    [[ "$r" == "$fr_role" ]] && { found=1; break; }
  done
  [[ $found -eq 0 ]] && unexpected+=("$fr_role")
done
if [[ ${#unexpected[@]} -gt 0 ]]; then
  echo "ERROR: Unexpected fragments (roles not in any manifest): ${unexpected[*]}" >&2
  echo "Either remove the stray fragment or add the role to a manifest." >&2
  exit 1
fi

# --- Compose tfvars (validating fragment shape line-by-line) ---
mkdir -p "$(dirname "$OUT_TFVARS")"
{
  echo "# Auto-generated by merge-image-versions.sh from per-role build fragments."
  echo "# Do not edit; do not commit."
  echo "image_versions = {"
  for role in "${expected_roles[@]}"; do
    line="$(cat "${FRAG_DIR}/${role}.tfvars-fragment")"
    # Pipeline builds are always clean (no --dev). Reject -dev suffixes:
    # if a fragment ever carries one, something bypassed the clean-build
    # contract (.claude/rules/build-deploy.md) and the deploy must not
    # consume it.
    # Hash alphabet is nix base32 (0-9 a-z minus e,o,t,u); use [a-z0-9]
    # to match. Aligning with tofu-wrapper.sh's IMAGE_FILENAME_PATTERN.
    if ! [[ "$line" =~ ^[[:space:]]*\"${role}\"[[:space:]]*=[[:space:]]*\"${role}-[a-z0-9]{8}\.img\"[[:space:]]*$ ]]; then
      echo "ERROR: Invalid fragment for role '${role}': ${line}" >&2
      echo "Expected shape: \"${role}\" = \"${role}-<hash>.img\" (no -dev suffix)" >&2
      exit 1
    fi
    # Re-emit with canonical 2-space indent, stripping any leading whitespace.
    printf '  %s\n' "${line#"${line%%[![:space:]]*}"}"
  done
  echo "}"
} > "$OUT_TFVARS"

echo "Wrote $OUT_TFVARS:"
cat "$OUT_TFVARS"

# --- Compose closure-paths.json from per-host closure files ---
{
  printf '{\n'
  first=1
  for host in "${CONTROL_PLANE_HOSTS[@]}"; do
    cp_file="${REPO_DIR}/build/closure-path-${host}.txt"
    if [[ ! -s "$cp_file" ]]; then
      echo "ERROR: Missing closure path for control-plane host '${host}': $cp_file" >&2
      echo "build:image job for '${host}' must emit build/closure-path-${host}.txt" >&2
      exit 1
    fi
    path="$(tr -d '[:space:]' < "$cp_file")"
    if [[ ! "$path" =~ ^/nix/store/[a-z0-9]+-.* ]]; then
      echo "ERROR: Invalid closure path for '${host}': $path" >&2
      exit 1
    fi
    [[ $first -eq 0 ]] && printf ',\n'
    printf '  "%s": "%s"' "$host" "$path"
    first=0
  done
  printf '\n}\n'
} > "$OUT_CLOSURES"

echo ""
echo "Wrote $OUT_CLOSURES:"
cat "$OUT_CLOSURES"
