approles:
  - name_template: "grafana_${env}"
    policy: "default-policy"
    sops_keys:
      role_id: "vault_approle_grafana_${env}_role_id"
      secret_id: "vault_approle_grafana_${env}_secret_id"
