#!/usr/bin/env bash
# Fixture test for framework/scripts/merge-image-versions.sh.
#
# The merge script is the only thing standing between a per-role build
# fragment going wrong and a partial image-versions.auto.tfvars reaching
# the deploy stage. Lock down its drift detection and shape validation
# so a future refactor does not silently weaken either.

set -euo pipefail

TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${TEST_DIR}/.." && pwd)"

source "${REPO_ROOT}/tests/lib/runner.sh"

SCRIPT="${REPO_ROOT}/framework/scripts/merge-image-versions.sh"

# Build a self-contained sandbox tree containing only what the merge
# script reads (manifests + applications.yaml + per-role fragments) and
# a copy of the script. The script computes REPO_DIR from its own
# location, so dropping a copy under <sandbox>/framework/scripts/
# isolates the test from the real repo's build/ directory.
make_sandbox() {
  local sb
  sb="$(mktemp -d "${TMPDIR:-/tmp}/test-merge-image-versions.XXXXXX")"
  mkdir -p \
    "${sb}/framework/scripts" \
    "${sb}/framework" \
    "${sb}/site" \
    "${sb}/build/image-versions"
  cp "$SCRIPT" "${sb}/framework/scripts/merge-image-versions.sh"
  # Minimal manifests covering one framework role, one site role, one
  # enabled app, and one disabled app (which must NOT show up in the
  # expected list).
  cat > "${sb}/framework/images.yaml" <<'EOF'
roles:
  alpha:
    category: nix
    host_config: site/nix/hosts/alpha.nix
EOF
  cat > "${sb}/site/images.yaml" <<'EOF'
roles:
  beta:
    category: nix
    host_config: site/nix/hosts/beta.nix
EOF
  cat > "${sb}/site/applications.yaml" <<'EOF'
applications:
  gamma:
    enabled: true
    environments:
      dev: { vmid: 999 }
  delta_disabled:
    enabled: false
    environments:
      dev: { vmid: 998 }
EOF
  echo "$sb"
}

write_happy_fragments() {
  local sb="$1"
  for r in alpha beta gamma; do
    printf '  "%s" = "%s-4ypjgkci.img"\n' "$r" "$r" \
      > "${sb}/build/image-versions/${r}.tfvars-fragment"
  done
  echo "/nix/store/4ypjgkci-gitlab-system-toplevel" \
    > "${sb}/build/closure-path-gitlab.txt"
  echo "/nix/store/s65mxam5-cicd-system-toplevel" \
    > "${sb}/build/closure-path-cicd.txt"
}

# Run the sandboxed copy of the script, capture exit code and combined
# stderr+stdout for assertion. Always restore set -e after capture
# (.claude/rules/platform.md "set -e kills before you can capture exit").
run_merge() {
  local sb="$1" out
  set +e
  out="$("${sb}/framework/scripts/merge-image-versions.sh" 2>&1)"
  local rc=$?
  set -e
  printf '%s\n' "$out"
  return $rc
}

# --- happy path: deterministic sorted output, both artifacts written ---
test_start "M1" "happy path produces sorted tfvars and closure-paths.json"
sb="$(make_sandbox)"
write_happy_fragments "$sb"
if run_merge "$sb" >/dev/null 2>&1; then
  expected_tfvars=$'# Auto-generated by merge-image-versions.sh from per-role build fragments.\n# Do not edit; do not commit.\nimage_versions = {\n  "alpha" = "alpha-4ypjgkci.img"\n  "beta" = "beta-4ypjgkci.img"\n  "gamma" = "gamma-4ypjgkci.img"\n}'
  actual_tfvars="$(cat "${sb}/site/tofu/image-versions.auto.tfvars")"
  if [[ "$actual_tfvars" == "$expected_tfvars" ]]; then
    if grep -q '"gitlab"' "${sb}/build/closure-paths.json" \
       && grep -q '"cicd"' "${sb}/build/closure-paths.json" \
       && grep -q '4ypjgkci-gitlab-system-toplevel' "${sb}/build/closure-paths.json"; then
      test_pass "happy path output is byte-stable and complete"
    else
      test_fail "closure-paths.json missing expected entries"
    fi
  else
    test_fail "tfvars output does not match expected (drift in formatting)"
    diff <(echo "$expected_tfvars") <(echo "$actual_tfvars") || true
  fi
else
  test_fail "happy path exited non-zero"
fi
rm -rf "$sb"

# --- determinism: two runs back-to-back produce identical output ---
test_start "M2" "merge output is byte-for-byte stable across runs"
sb="$(make_sandbox)"
write_happy_fragments "$sb"
run_merge "$sb" >/dev/null 2>&1 || true
first="$(cat "${sb}/site/tofu/image-versions.auto.tfvars")"
run_merge "$sb" >/dev/null 2>&1 || true
second="$(cat "${sb}/site/tofu/image-versions.auto.tfvars")"
if [[ "$first" == "$second" ]]; then
  test_pass "second run produced identical tfvars"
else
  test_fail "second run produced different tfvars"
fi
rm -rf "$sb"

# --- missing fragment: deploy must NOT proceed ---
test_start "M3" "missing fragment fails closed with actionable message"
sb="$(make_sandbox)"
write_happy_fragments "$sb"
rm "${sb}/build/image-versions/alpha.tfvars-fragment"
out="$(run_merge "$sb")" && rc=0 || rc=$?
if [[ $rc -ne 0 ]] && grep -q "Missing or empty fragments for: alpha" <<< "$out"; then
  test_pass "missing fragment for 'alpha' fails with named role"
else
  test_fail "expected non-zero exit + named role; got rc=$rc, output: $out"
fi
rm -rf "$sb"

# --- unexpected fragment (drift in the other direction) ---
test_start "M4" "unexpected fragment fails closed with named role"
sb="$(make_sandbox)"
write_happy_fragments "$sb"
printf '  "%s" = "%s-4ypjgkci.img"\n' "stranger" "stranger" \
  > "${sb}/build/image-versions/stranger.tfvars-fragment"
out="$(run_merge "$sb")" && rc=0 || rc=$?
if [[ $rc -ne 0 ]] && grep -q "Unexpected fragments .* stranger" <<< "$out"; then
  test_pass "unexpected fragment 'stranger' fails with named role"
else
  test_fail "expected non-zero exit + named role; got rc=$rc, output: $out"
fi
rm -rf "$sb"

# --- malformed fragment: wrong role on the line ---
test_start "M5" "fragment with wrong role label fails"
sb="$(make_sandbox)"
write_happy_fragments "$sb"
echo '  "wrong" = "alpha-4ypjgkci.img"' > "${sb}/build/image-versions/alpha.tfvars-fragment"
out="$(run_merge "$sb")" && rc=0 || rc=$?
if [[ $rc -ne 0 ]] && grep -q "Invalid fragment for role 'alpha'" <<< "$out"; then
  test_pass "wrong-role fragment fails with named role"
else
  test_fail "expected rc!=0 + named role; got rc=$rc, output: $out"
fi
rm -rf "$sb"

# --- malformed fragment: wrong filename role ---
test_start "M6" "fragment with mismatched filename role fails"
sb="$(make_sandbox)"
write_happy_fragments "$sb"
echo '  "alpha" = "beta-4ypjgkci.img"' > "${sb}/build/image-versions/alpha.tfvars-fragment"
out="$(run_merge "$sb")" && rc=0 || rc=$?
if [[ $rc -ne 0 ]] && grep -q "Invalid fragment for role 'alpha'" <<< "$out"; then
  test_pass "mismatched-filename fragment fails with named role"
else
  test_fail "expected rc!=0 + named role; got rc=$rc, output: $out"
fi
rm -rf "$sb"

# --- -dev suffix must be rejected (clean-build contract) ---
test_start "M7" "fragment with -dev suffix is rejected"
sb="$(make_sandbox)"
write_happy_fragments "$sb"
echo '  "alpha" = "alpha-4ypjgkci-dev.img"' > "${sb}/build/image-versions/alpha.tfvars-fragment"
out="$(run_merge "$sb")" && rc=0 || rc=$?
if [[ $rc -ne 0 ]] && grep -q "Invalid fragment for role 'alpha'" <<< "$out"; then
  test_pass "dev-suffix fragment is rejected"
else
  test_fail "expected rc!=0 + named role; got rc=$rc, output: $out"
fi
rm -rf "$sb"

# --- missing closure path for a control-plane host ---
test_start "M8" "missing control-plane closure path fails closed"
sb="$(make_sandbox)"
write_happy_fragments "$sb"
rm "${sb}/build/closure-path-cicd.txt"
out="$(run_merge "$sb")" && rc=0 || rc=$?
if [[ $rc -ne 0 ]] && grep -q "Missing closure path for control-plane host 'cicd'" <<< "$out"; then
  test_pass "missing cicd closure path fails with named host"
else
  test_fail "expected rc!=0 + named host; got rc=$rc, output: $out"
fi
rm -rf "$sb"

# --- invalid closure path (not a /nix/store path) ---
test_start "M9" "invalid closure path is rejected"
sb="$(make_sandbox)"
write_happy_fragments "$sb"
echo "/var/tmp/oops" > "${sb}/build/closure-path-cicd.txt"
out="$(run_merge "$sb")" && rc=0 || rc=$?
if [[ $rc -ne 0 ]] && grep -q "Invalid closure path for 'cicd'" <<< "$out"; then
  test_pass "non-/nix/store closure path is rejected"
else
  test_fail "expected rc!=0 + named host; got rc=$rc, output: $out"
fi
rm -rf "$sb"

# --- disabled app must not be in expected role list ---
test_start "M10" "disabled application is not required"
sb="$(make_sandbox)"
write_happy_fragments "$sb"
# delta_disabled has no fragment; if it were in the expected list, M3
# would have failed instead. Verify by also confirming that a fragment
# FOR a disabled app is treated as unexpected (drift detection).
printf '  "%s" = "%s-4ypjgkci.img"\n' "delta_disabled" "delta_disabled" \
  > "${sb}/build/image-versions/delta_disabled.tfvars-fragment"
out="$(run_merge "$sb")" && rc=0 || rc=$?
if [[ $rc -ne 0 ]] && grep -q "Unexpected fragments .* delta_disabled" <<< "$out"; then
  test_pass "disabled app is excluded from expected list and fails as unexpected"
else
  test_fail "expected disabled app to be unexpected; got rc=$rc, output: $out"
fi
rm -rf "$sb"

# --- Regression guard for the hash-alphabet bug (sub-claude found this).
# The original regex used [a-f0-9]+ which rejects nix base32 hashes
# containing g-z (minus e,o,t,u). Hard-code a hash that exercises the
# non-hex letters so any future regex narrowing is caught immediately.
test_start "M11" "fragment with non-hex base32 hash chars is accepted (regression guard)"
sb="$(make_sandbox)"
write_happy_fragments "$sb"
echo '  "alpha" = "alpha-jklmnpqr.img"' > "${sb}/build/image-versions/alpha.tfvars-fragment"
out="$(run_merge "$sb")" && rc=0 || rc=$?
if [[ $rc -eq 0 ]]; then
  if grep -q '"alpha" = "alpha-jklmnpqr.img"' "${sb}/site/tofu/image-versions.auto.tfvars"; then
    test_pass "non-hex base32 hash 'jklmnpqr' is accepted by fragment regex"
  else
    test_fail "non-hex hash exited 0 but did not appear in tfvars output"
  fi
else
  test_fail "non-hex base32 hash 'jklmnpqr' was rejected (rc=$rc, output: $out)"
fi
rm -rf "$sb"

runner_summary
