variable "dns1_vm_id" {
  description = "Proxmox VM ID for dns1 (pinned, from config.yaml)"
  type        = number
}

variable "dns2_vm_id" {
  description = "Proxmox VM ID for dns2 (pinned, from config.yaml)"
  type        = number
}

variable "environment" {
  description = "Environment name: prod or dev"
  type        = string

  validation {
    condition     = contains(["prod", "dev"], var.environment)
    error_message = "environment must be 'prod' or 'dev'"
  }
}

variable "vlan_id" {
  description = "VLAN ID for the environment"
  type        = number
}

variable "dns1_ip" {
  description = "IP address for dns1 (pre-assigned via DHCP reservation)"
  type        = string
}

variable "dns1_mac" {
  description = "MAC address for dns1 (pre-assigned for DHCP reservation)"
  type        = string
}

variable "dns2_ip" {
  description = "IP address for dns2 (pre-assigned via DHCP reservation)"
  type        = string
}

variable "dns2_mac" {
  description = "MAC address for dns2 (pre-assigned for DHCP reservation)"
  type        = string
}

variable "node_names" {
  description = "List of Proxmox node names (e.g., [\"pve01\",\"pve02\",\"pve03\"]). At least 2 nodes required for anti-affinity."
  type        = list(string)

  validation {
    condition     = length(var.node_names) >= 2
    error_message = "At least 2 nodes are required for DNS anti-affinity (dns1 and dns2 on different nodes)."
  }
}

variable "image" {
  description = "Proxmox file ID for the DNS image (e.g., local:iso/dns-v0.1.img)"
  type        = string
}

variable "ssh_pubkey" {
  description = "Operator SSH public key for cloud-init"
  type        = string
}

variable "operator_ssh_pubkey" {
  description = "Operator workstation SSH public key from config.yaml"
  type        = string
  default     = ""
}

variable "pdns_api_key" {
  description = "PowerDNS API key (from SOPS via TF_VAR_pdns_api_key)"
  type        = string
  sensitive   = true
}

variable "storage_pool" {
  description = "ZFS pool name for VM disks"
  type        = string
  default     = "local-zfs"
}

variable "acme_server_url" {
  description = "ACME directory URL (Pebble in dev, Let's Encrypt in prod)"
  type        = string
}

variable "acme_ca_cert" {
  description = "PEM content of the ACME server's CA cert (empty = use system CA bundle)"
  type        = string
  default     = ""
}

variable "gateway_ip" {
  description = "Gateway IP for recursive DNS resolution (environment-specific)"
  type        = string
}

variable "dns_domain" {
  description = "DNS domain for this environment (e.g., prod.example.com). Used by the recursor to forward local zone queries to the co-located authoritative."
  type        = string
}

variable "zone_data" {
  description = "JSON-encoded zone data for this environment (generated by main.tf from config.yaml). Delivered via CIDATA and loaded by pdns-zone-load at boot."
  type        = string
}

variable "domain" {
  description = "Base domain (written to CIDATA to trigger recreation on domain change)"
  type        = string
  default     = ""
}

variable "dns_servers" {
  description = "DNS server IPs"
  type        = list(string)
  default     = []
}

variable "search_domain" {
  description = "DNS search domain"
  type        = string
  default     = ""
}
